 <div class="wrap-list-serviecs clearfix">
 	<h4>MÆRKER VI FORHANDLER</h4>
	<ul class="list-serviecs clearfix">
	   <li><a href="#">Aida</a></li>
	   <li><a href="#">Fiskars</a></li>
	   <li><a href="#">Light Shine</a></li>
	   <li><a href="#">Remington</a></li>
	   <li><a href="#">Albaline </a></li>
	   <li><a href="#">Funktion </a></li>
	   <li><a href="#">Melissa</a></li>
	   <li><a href="#">Rikki Tikki Jul </a></li>
	   <li><a href="#">Amager </a></li>
	   <li><a href="#">Galzone </a></li>
	   <li><a href="#">Melitta </a></li>
	   <li><a href="#">Rosenborg</a></li>
	   <li><a href="#">Isenkram </a></li>
	   <li><a href="#">Georg Jensen </a></li>
	   <li><a href="#">Mette Blomsterberg </a></li>
	   <li><a href="#">Rosendahl </a></li>
	   <li><a href="#">Andersen </a></li>
	   <li><a href="#">Grundig </a></li>
	   <li><a href="#">Microplane </a></li>
	   <li><a href="#">Rosti </a></li>
	   <li><a href="#">Babyliss </a></li>
	   <li><a href="#">Hammarplast </a></li>
	   <li><a href="#">Min Søsters Kage </a></li>
	   <li><a href="#">Rømertopf </a></li>
	   <li><a href="#">Bodum </a></li>
	   <li><a href="#">Herstal </a></li>
	   <li><a href="#">Moulinex </a></li>
	   <li><a href="#">Scanpan </a></li>
	   <li><a href="#">Bosch </a></li>
	   <li><a href="#">Hilfling </a></li>
	   <li><a href="#">Nielsen </a></li>
	   <li><a href="#">Severin </a></li>
	   <li><a href="#">Brabantia </a></li>
	   <li><a href="#">Design </a></li>
	   <li><a href="#">Light Nilfisk </a></li>
	   <li><a href="#">Sirius </a></li>
	   <li><a href="#">Braun </a></li>
	   <li><a href="#">Hoffmann </a></li>
	   <li><a href="#">Nuance </a></li>
	   <li><a href="#">Södahl </a></li>
	   <li><a href="#">Conzept </a></li>
	   <li><a href="#">Holmegaard </a></li>
	   <li><a href="#">OBH </a></li>
	   <li><a href="#">Sodastream </a></li>
	   <li><a href="#">Denver </a></li>
	   <li><a href="#">Hoptimist</a></li>
	   <li><a href="#">Oral-B </a></li>
	   <li><a href="#">Soehnle </a></li>
	   <li><a href="#">Duracell </a></li>
	   <li><a href="#">Jacob Jensen </a></li>
	   <li><a href="#">Oxo Parkone </a></li>
	   <li><a href="#">Tefal </a></li>
	   <li><a href="#">Elworks </a></li>
	   <li><a href="#">Kähler </a></li>
	   <li><a href="#">Peugeot </a></li>
	   <li><a href="#">Thermos </a></li>
	   <li><a href="#">Emsa </a></li>
	   <li><a href="#">Kenwood </a></li>
	   <li><a href="#">Philips Plast </a></li>
	   <li><a href="#">Tiger </a></li>
	   <li><a href="#">Eva </a></li>
	   <li><a href="#">Krups </a></li>
	   <li><a href="#">Team Plast1 </a></li>
	   <li><a href="#">Westmark</a></li>
	   <li><a href="#">Eva Solo </a></li>
	   <li><a href="#">Le Creuset </a></li>
	   <li><a href="#">Pyrex </a></li>
	   <li><a href="#">Zone</a></li>
	   <li><a href="#">Eva Trio </a></li>
	   <li><a href="#">Leifheit </a></li>
	   <li><a href="#">Raadvad </a></li>
	</ul>
	<h4>BETINGELSER & VILKÅR</h4>
	<ul class="list-serviecs1 clearfix">
		<li><a href="#">Sådan handler du</a></li>
		<li><a href="#">Fragtfri forsendelse</a></li>
		<li><a href="#">Bytteservice</a></li>
		<li><a href="#">Sikker betaling</a></li>
		<li><a href="#">Handelsbetingelser</a></li>
	</ul>
</div><!--eachBox wrap-list-serviecs--> 